[platformio]
src_dir = main
include_dir = main

[env:esp32s3]
platform = espressif32@6.8.1
board = esp32-s3-devkitc-1
framework = espidf

upload_port = /dev/cu.usbmodem21201
monitor_port = /dev/cu.usbmodem21201
monitor_speed = 115200

board_build.partitions = partitions.csv
board_build.flash_mode = dio
board_build.flash_size = 8MB
board_build.f_flash = 80000000L

build_flags =
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_DEMO_CONF_INCLUDE_SIMPLE

board_build.cmake_extra_args =
    -DEXTRA_COMPONENT_DIRS=${PROJECT_DIR}/components
